apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-service
          image: nginx:latest
          ports:
            - containerPort: 80

          env:
            - name: SERVICE_NAME
              value: "product-service"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 80

          livenessProbe:
            httpGet:
              path: /
              port: 80
