apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service
          image: nginx:latest
          ports:
            - containerPort: 80

          env:
            - name: SERVICE_NAME
              value: "user-service"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
